pr_checkout: improve error handling and user friendliness
* Add `is_git_repo <DIR> <USER>|'' <REPO>|'' <REMOTE>|''` for checking if <DIR> is a valid git repo,
  and if that repo has a remote pointing to github.com/<USER>/<REPO>.
* Add `is_repo_clean <DIR>` for checking if the repo in <DIR> is clean.
* Add `prompt` function for asking the user for confirmation.
* Add `git_stash_if_needed <DIR>` function that offers to call `git stash`
  if the repo is not clean.

* Validate the PR number.
* Print information about the current working dir and the PR that is being fetched.
* Validate that  is a git repo.
* Offer to push uncommited changes to git stash.

diff --git a/pr_checkout b/pr_checkout
--- a/pr_checkout
+++ b/pr_checkout
@@ -14,19 +14,72 @@
 set -ueo pipefail
 
 if [ -z "${1+x}" ] ; then
-    echo "Usage: ./pr_checkout <123>"
+    echo "[!] Usage: ./pr_checkout <number>"
     exit
 fi
 
 DIR=$(test -d ${DIR:-.} && cd ${DIR:-.} || true && pwd)
-PR="$1"
 UPSTREAM="${UPSTREAM:-upstream}"
 MASTER="${MASTER:-master}"
 
+function prompt {
+    while true; do
+        read -p "$1" choice
+        case "$choice" in
+            y|Y|'') return 0;;
+            n|N) return 1;;
+            *) ;;
+        esac
+    done
+}
+
+function is_git_repo {
+    dir=$1; user=${2:-}; repo=${3:-}; upstream=${4:-};
+    if ! git -C $dir rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+        return 1;
+    fi
+    if ! test -z "$user" || ! test -z "$repo" || ! test -z $upstream; then
+        repo_regex="^${upstream:-.*}[[:space:]]*\
+((https://github\.com/)|(git@github\.com:))${user:-.*}/${repo:-.*}(\.git)?"
+        git -C $dir remote -v | grep -qE "$repo_regex"
+    else
+        return 0
+    fi
+}
+
+function is_repo_clean { git -C $1 diff-index --quiet HEAD --; }
+
+function git_stash_if_needed {
+    if ! is_repo_clean $1; then
+        echo "[!] Repo '$1' contains uncommited changes."
+        if ! prompt "[?] Stash uncommitted changes [Y/n]? "; then
+            echo "[!] Unable to proceed. Good bye."; exit 1
+        fi
+        git -C $1 stash push
+    fi
+}
+
+echo "[>] Executing from '$DIR'."
+
 cd "$DIR"
+pr_num_regex='^([0-9]+)$'
+input=$1
+if [[ $input =~ $pr_num_regex ]]; then
+    PR="${BASH_REMATCH[1]}"
+    if ! is_git_repo $DIR '' '' $UPSTREAM; then
+        echo "[!] Dir '$DIR' is not a valid git repo."
+        exit 1
+    fi
+
+    git_stash_if_needed $DIR
+    echo "[>] Attempting to fetch PR #$PR from '$UPSTREAM' ($(git remote get-url $UPSTREAM))."
+else
+    echo "[!] '$input' is not a valid number."
+    exit 1
+fi
 
 # delete existing branch
 git checkout -q "$MASTER"
 git fetch --prune "$UPSTREAM" "$MASTER" "+refs/pull/$PR/head:pr/$PR"
-git merge --ff-only "$UPSTREAM/$MASTER"
+echo -n "[>] Fast-forwarding '$MASTER' branch... "; git merge --ff-only "$UPSTREAM/$MASTER"
 git checkout "pr/$PR"
